2808 - introduced es6 to the component
adaptlearning/adapt-component pull request #1
Opened 2022-05-09 10:15 UTC by eleanor-heath

https://github.com/adaptlearning/adapt_framework/issues/2808

2022-05-09 11:17 UTC, cahirodoherty-learningpool approved these changes
👀

2022-05-09 13:03 UTC, ethan-lp approved these changes

2022-05-10 09:38 UTC, oliverfoster requested changes

2022-05-10 09:38 UTC, oliverfoster commented on js/adapt-contrib-componentName.js
> +export default Adapt.register('componentName', ComponentName);
Move to a separate file as with other plugins. `export default ComponentNameView;` here instead.

2022-05-10 09:38 UTC, oliverfoster commented on js/adapt-contrib-componentName.js
> +  }
At the bottom `ComponentNameView.template = 'componentName';`

2022-05-10 09:38 UTC, oliverfoster commented on js/adapt-contrib-componentName.js
> +class ComponentName extends ComponentView {
```suggestion
class ComponentNameView extends ComponentView {
```

2022-05-10 10:20 UTC, oliverfoster requested changes

2022-05-10 10:20 UTC, oliverfoster commented on js/adapt-contrib-componentName.js
> +import ComponentNameModel from './ComponentNameModel';
You'll need to add the file `js/ComponentNameModel.js`

Something like:
```js
import ComponentModel from 'core/js/models/componentModel';

export class ComponentNameModel extends ComponentModel {}
```

2022-05-10 10:29 UTC, oliverfoster approved these changes

2022-05-23 11:02 UTC, merged